user:
  superadmin:
    username: superadmin
    password: gqkt111!
  dean:
#    每次切换
    username: Auto_dean002
#    每次切换
    user_code: Auto_dean_code002
    phone: 17601616126
    email: 411861376@qq.com
  dean_cms:
#    每次切换
    username: Auto_dean_cms002
    password: Autotest

school_name: 智慧大学

url: https://www.gqkt.cn/

mysql:
  db: trading_system
  host: 120.53.230.254
  password: william
  port: 3306
  user: root

redis:
  host: 120.53.230.254
  port: 6379
  db: 0

jenkins:
  url: http://120.53.230.254:8080

dingding_group:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=b1572bfb00b878a14dde02f96d99398dc98623111ef56d10aeb937fefa8e1b52