# 全局变量配置（只需修改这里的序号）
test_suffix: 100 # 测试环境序号

# 部署环境配置（控制浏览器驱动和用例执行）
部署环境:
  是否本地部署: true  # true: 本地部署，false: 网络部署
  是否Headless模式: true  # true: 使用Headless模式（无界面），false: 使用有界面模式（需要显示环境）
school_name: 智慧大学
# url: https://www.gqkt.cn/
url: http://192.168.200.215/

user:
  # 初始管理员
  initial_admin:
    username: superadmin
    password: 123

  # 初始管理员
  # initial_admin:
  #   username: superadmin
  #   password: gqkt111!
  # 教务管理员
  dean:
    姓名: &dean_name Auto_dean{suffix}
    工号: &dean_code Auto_dean_code{suffix}
    手机: "15100000001"
    邮箱: Autotest001@xuetangx.com
  # CMS 教务管理员
  dean_cms:
    username: *dean_code
    password: Xuetangx2026
  # 专业管理员
  prof:
    姓名: &prof_name Auto_prof{suffix}
    工号: &prof_code Auto_prof_code{suffix}
    手机: "15100000002"
    邮箱: Autotest002@xuetangx.com
  # CMS 专业管理员
  prof_cms:
    username: *prof_code
    password: Xuetangx2026

# 院系信息
department:
  院系名称: &dept_name auto_dept{suffix}
  院系代码: Auto_dept{suffix}

major:
  专业名称: &major_name auto_major{suffix}
  学校专业代码: "070102"
  国家专业代码: "070102"
  所属院系: *dept_name
  专业负责人: *prof_name
  专业建设层次: 国家一流本科专业
  专业特色标签:
    - 国家级特色专业
    - 省级特色专业

admin_class:
  行政班名称: Auto_admin_class{suffix}
  行政班编号: Auto_admin_class_code{suffix}
  行政班描述: Auto_admin_class_desc{suffix}
  所属学院: *dept_name
  所属专业: *major_name
  年级: 2025级
  行政班描述: 行政班描述

course:
  课程名称: Auto_course{suffix}
  课程代码: Auto_course_code{suffix}
  所属学院: *dept_name
  课程负责人: *prof_name
  是否一流课程: true
  课程描述: 课程描述

training_program:
  方案名称: Auto_training_program{suffix}
  关联专业: *major_name
  培养类型: 主修
  培养层次: 本科
  学制: 4年
  授予学位: 工学学士

mysql:
  db: trading_system
  host: 120.53.230.254
  password: william
  port: 3306
  user: root

redis:
  host: 120.53.230.254
  port: 6379
  db: 0

jenkins:
  url: http://120.53.230.254:8080

dingding_group:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=b1572bfb00b878a14dde02f96d99398dc98623111ef56d10aeb937fefa8e1b52
