user:
  superadmin:
    username: superadmin
    password: 111
  dean:
#    每次切换
    username: Auto_dean006
#    每次切换
    user_code: Auto_dean_code006
    phone: 17601616126
    email: 411861376@qq.com
  dean_cms:
#    每次切换
    username: Auto_dean_cms006
    password: Autotest

school_name: 演示大学

url: http://192.168.200.204:5173/

mysql:
  db: trading_system
  host: 120.53.230.254
  password: william
  port: 3306
  user: root

redis:
  host: 120.53.230.254
  port: 6379
  db: 0

jenkins:
  url: http://120.53.230.254:8080

dingding_group:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=b1572bfb00b878a14dde02f96d99398dc98623111ef56d10aeb937fefa8e1b52