# 全局变量配置（只需修改这里的序号）
test_suffix: 11  # 测试环境序号

school_name: 智慧大学
url: https://www.gqkt.cn/
user:
  # 超级管理员
  superadmin:
    username: superadmin
    password: gqkt111!
  # CMS 教务管理员
  dean_cms:
    username: Auto_dean_cms{suffix}
    password: Autotest
  # 教务管理员
  dean:
    姓名: Auto_dean{suffix}
    工号: Auto_dean_code{suffix}
    手机: 15100000001
    邮箱: Autotest001@xuetangx.com
  # CMS 专业管理员
  prof_cms:
    username: Auto_prof_cms{suffix}
    password: Autotest
  # 专业管理员
  prof:
    姓名: Auto_prof{suffix}
    工号: Auto_prof_code{suffix}
    手机: 15100000002
    邮箱: Autotest002@xuetangx.com
# 院系信息
department:
  院系名称: auto_dept{suffix}
  院系代码: Auto_dept{suffix}








mysql:
  db: trading_system
  host: 120.53.230.254
  password: william
  port: 3306
  user: root

redis:
  host: 120.53.230.254
  port: 6379
  db: 0

jenkins:
  url: http://120.53.230.254:8080

dingding_group:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=b1572bfb00b878a14dde02f96d99398dc98623111ef56d10aeb937fefa8e1b52